### ISSUE TITLE
Review of new basic test profile

### ISSUE THREAD

**Issue by segoerke** [opengeospatial/ets-wfs11#1]
I just pushed Ingo's work to have a basic test profile of WFS 1.1.0 tests. These basic tests do not require specific test data. There is a new branch "new-basic-profile" consisting of these changed tests.

We have to review this basic tests and check how to further improve them to replace the current "basic" tests.

**Comment by bermud** [comment]
Fixed in https://github.com/opengeospatial/ets-wfs11/commit/32384c32978eef0a24567edb562acff1590eff5d
