### ISSUE TITLE
WFS 1.1.0 conformance test wfs-1.1.0-Basic-GetCapabilities-tc16.5 fails

### ISSUE THREAD

**Issue by segoerke** [opengeospatial/ets-wfs11#19]
WFS 1.1.0 conformance test wfs-1.1.0-Basic-GetCapabilities-tc16.5
fails with:

A sequence of more than one item is not allowed as the first argument
of lower-case() ("service", "request")

The ExceptionReport (below) contains two Exception elements, which is
allowed according to section 7.7 Exception reporting of the WFS
1.1.0 specification.

--- <?xml version="1.0" ?> <ExceptionReport version="1.1.0"
xmlns="http://www.opengis.net/ows"
xmlns:ows="http://www.opengis.net/ows"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.opengis.net/ows
http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="MissingParameterValue"
locator="service"><ows:ExceptionText> <![CDATA[ The request does not
contain the required service parameter, for WFS requests this should
be set to 'WFS'. ]]> </ows:ExceptionText> </ows:Exception>
<ows:Exception exceptionCode="MissingParameterValue"
locator="request"><ows:ExceptionText> <![CDATA[ The request does not
contain the required request parameter. ]]> </ows:ExceptionText>
</ows:Exception> </ExceptionReport> ---

Could it be that the validator cannot handle ExceptionReports with two
Exceptions?

**Comment by dbretschneider** [comment]
Which service do you used? I have executed the Test-Suite against [deegree 3.3.6](http://cite.lat-lon.de/deegree-webservices-3.3.6/services/wfs110?):

**Request**
`http://cite.lat-lon.de/deegree-webservices-3.3.6/services/wfs110?version=1.1.0&request~GetCapabilities!service~WFS`

**Response**
``` xml
<ows:Exception exceptionCode="MissingParameterValue" locator="service">
    <ows:ExceptionText>The 'SERVICE' parameter is missing.</ows:ExceptionText>
</ows:Exception>
```

**Comment by dstenger** [comment]
Can you please provide a service to reproduce this error?

**Comment by dstenger** [comment]
As there are no test services and no specific applications available, the issue can be closed. If the problem occurs again, the issue can be reopened.
