### ISSUE TITLE
Aggregate geometry types not being checked in the GetCapabilities

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs11#37]
Some servers does not fully support certain operations on aggregate geometries, so that a number of tests using these as geometry operands fail: 29.4, 200.3, 201.3, 205.1. 

Even  restricting the  WFS Capabilities by excluding the aggregate geometry types from the supported object types in, which conforms to the specification. The test does not check this section of the Capabilities document, so these test cases will still fail.

Test 201.2 fails because it uses a filter with an aggregate geometry operand, although the filter capabilities do not allow such an operand.

Originally reported by Smallworld at: https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=633

**Comment by bermud** [comment]
@dstenger will contact Tony G.  so he can make the folder available for further testing.

**Comment by dstenger** [comment]
Test 201.2:
Why does the filter use an aggregate geometry type? Wouldn't a simple geometry type be fine as well? To fix this, the filter of the test has to be simplified.
Same applies to 205.1.

How were the test data imported? They include aggregated geometries which are not supported by the server (e.g. 205.1. returns a MultiPoint).

**Comment by dstenger** [comment]
We executed the WFS 1.1.0. test suite with the service provided by Tony G.

Result of the analysis:

In total 5 Tests fail:
 * wfs:wfs-1.1.0-Basic-GetFeature-tc29.4
  * FAILURE: Expected at least one sf:AggregateGeoFeature instances in response
 * wfs:wfs-1.1.0-Basic-GetFeature-tc200.3 
  * FAILURE: Expected one or more sf:AggregateGeoFeature instances in response (0 features included)
 * wfs:wfs-1.1.0-Basic-GetFeature-tc201.2
  * Response: !ExceptionReport "Geometry could not be converted" 
 * wfs:wfs-1.1.0-Basic-GetFeature-tc201.3
  * Response: !ExceptionReport "Unable to parse GMLGeometry definition in 'Intersects'-operation!"
 * wfs:wfs-1.1.0-Basic-GetFeature-tc205.1
  * Response: !ExceptionReport "Geometry could not be converted"

Analysis:
 * 201.2 and 205.1: In both cases a MultiGeometry is used in the filter. A possible solution, as stated above, is to use a simple geometry.
 * 29.4 and 200.3: Features of FeatureType ''sf:AggregateGeoFeature'' are not returned by the service (they probably contain complex geometries).
 * 201.3: The requested geometry cannot be parsed. However, the FeatureType ''sf:AggregateGeoFeature'' is requested and previously described error would also occur.

However, ''table 1 — Compliance level capabilities matrix'' in ''Geography Markup Language (GML) – Simple features profile, version 1.0.0'' (is linked on http://cite.opengeospatial.org/teamengine/about/wfs/1.1.0/site/) states that support of requests with multi geometries is mandatory as Level SF-0 has to be supported by the service.

As this specification is a prerequisite for the test suite, we think that the behaviour of the test suite is correct and no fix has to be provided.

**Comment by dstenger** [comment]
As there is no fix necessary, the issue is closed.
