### ISSUE TITLE
Complete WFS 1.1.0 Basic Test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs11#42]
Complete the WFS 1.1.0 Basic test
- It should pass with some available WFS severs that have no data
- Errors should be clear and should provide possible fix (what to expect)

List of servers are here:
https://docs.google.com/spreadsheets/d/1no8wfRhM9xU_SipM-MLCxFgtv8P6vJgTEb7j9kT-Mpk/pubhtml?gid=0&single=true

**Comment by segoerke** [comment]
With the current version of the Test Suite, it is possible to test successfully implementations which are not using the WFS 1.1.0 CITE Test data.

The following example is not using the test data and passing the tests on beta:
http://demo.deegree.org/utah-workspace/services/wfs110?request=GetCapabilities&service=WFS

**Comment by segoerke** [comment]
@bermud I think the issue can be closed now.

**Comment by bermud** [comment]
@segoerke, Thank you very much for advancing this issue.  Can you please provide urls of other services which are not deegree based. Which ones passed from the list of servers provided?

**Comment by segoerke** [comment]
http://services.nationalmap.gov/arcgis/services/WFS/geonames/MapServer/WFSServer?request=GetCapabilities&service=WFS
For this one, the Mime-Type of DescribeFeatureType Responses is not "text/xml; subtype=gml/3.1.1", so several DescribeFeatureType-Tests are failing.

For us, the Response Content-Type is a valid way to check for the Mime-Type of the response.
This behaviour is the same for all ArcGIS Server services from the list.

http://mrdata.usgs.gov/wfs/ds801?request=GetCapabilities&service=WFS&version=1.1.0
Responds with HTML format for several requests -> wrong default behaviour

http://cida.usgs.gov/nwc/geoserver/NHDPlusCatchments/ows?
Has invalid FeatureType names

So, none of the services in the list is passing the tests, they all have issues with requirements from the WFS 1.1.0 specification.

**Comment by dstenger** [comment]
We analysed the list and all services have a major shortcoming preventing it from passing the test suite.

Result of the evaluation:

|USGS Service|URL|Result|
|------------|---|------|
|WFS/geonames|http://services.nationalmap.gov/arcgis/services/WFS/geonames/MapServer/WFSServer?request=GetCapabilities&service=WFS|POST Encoding not implemented|
|WFS/govunits|http://services.nationalmap.gov/arcgis/services/WFS/govunits/MapServer/WFSServer|POST Encoding not implemented|
|WFS/structures|http://services.nationalmap.gov/arcgis/services/WFS/structures/MapServer/WFSServer|POST Encoding not implemented|
|WFS/transportation|http://services.nationalmap.gov/arcgis/services/WFS/transportation/MapServer/WFSServer|POST Encoding not implemented|
|WFS/Geochemical and mineralogical data from soils in the conterminous United States|http://mrdata.usgs.gov/wfs/ds801?request=getcapabilities&service=WFS&version=1.0.0&|POST Encoding not implemented|
|WFS/National Geochemical Database: Rock|http://mrdata.usgs.gov/wfs/ngdbrock?request=getcapabilities&service=WFS&version=1.0.0&|POST Encoding not implemented|
|WFS/Geologic maps of US states|http://mrdata.usgs.gov/wfs/sgmc?request=getcapabilities&service=WFS&version=1.0.0&|POST Encoding not implemented|
|SOS/Center for Integrated Data Analytics|http://cida.usgs.gov/ngwmn_cache/sos|No WFS|
|SOS/Aggregate Water Use Data System (AWUDS)|https://cida.usgs.gov/nwc/thredds/sos/watersmart/county_data/AWUDS.nc|No WFS|
|WFS/NHDPlus|http://cida.usgs.gov/nwc/geoserver/NHDPlusCatchments/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=NHDPlusCatchments:mvw_catchments&maxFeatures=100|Capabilities already broken: Spaces in element Name (e.g. NHDPlusCatchments:NHDPlus V2_catchments)|
|WFS/National Atlas Congressional Districts of the United States|http://webservices.nationalatlas.gov/arcgis/services/cgd113p010g/MapServer/WFSServer?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TypeName=cgd113p010g|WFS not reachable|
|WCS/ EDC Land Cover|http://isse.cr.usgs.gov/ArcGIS/services/LandCover/USGS_EDC_LandCover/MapServer/WCSServer?request=GetCapabilities&service=WCS|No WFS|
|WCS/ National Elevation Dataset|http://ags.cr.usgs.gov/ArcGIS/services/NED_1/MapServer/WCSServer?request=GetCapabilities&service=WCS|No WFS|
|WFS/ Earth Resources Observation and Science (EROS) Center|http://ags.cr.usgs.gov/ArcGIS/services/Feature_Service/MapServer/WFSServer?request=GetCapabilities&service=WFS|WFS not reachable|
|WCS/TNM_LandCover (MapServer)|http://raster.nationalmap.gov/ArcGIS/services/TNM_LandCover/MapServer/WCSServer?request=GetCapabilities&service=WCS|No WFS|

So, we have to search for some other service without a major shortcoming.

**Comment by bermud** [comment]
@dstenger, please look into only doing GET for the basic.

**Comment by dstenger** [comment]
Test results can be summarized on following wiki page: https://github.com/opengeospatial/ets-wfs11/wiki/WFS-1.1.0-Servers-Tested-with-the-Test-that-requires-no-data

**Comment by bermud** [comment]
Can we simplify the test, so it only exercises the GET request?

**Comment by dstenger** [comment]
**Current status:**

See Wiki page: https://github.com/opengeospatial/ets-wfs11/wiki/WFS-1.1.0-Servers-Tested-with-the-Test-that-requires-no-data

Two tests have to be adjusted:
 * Failure: DefaultSRS value is not a valid URI
  * Test: ctl:SchematronValidatingParser
  * Solution: Capabilities.sch is adjusted to accept experimental encodings (e.g. urn:x-ogc:def:crs:EPSG:4326).
 * Failure: MIME type not using "text/xml; subtype=gml/3.1.1"
  * Test: wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc4
  * Solution: "text/xml" is accepted as content type in response header.

**Comment by dstenger** [comment]
Fixes for two failures were implemented and are provided via pull requests:
 * Failure: DefaultSRS value is not a valid URI
  * #56
 * Failure: MIME type not using "text/xml; subtype=gml/3.1.1"
  * #57 
Both fixes will be part of the next release.

**Comment by dstenger** [comment]
Both pull requests (#56 and #57) were merged into master branch (after having done tests).
The fixes will be part of the upcoming release.
