### ISSUE TITLE
wfs:wfs-1.1.0-Basic-GetCapabilities-tc12 fails if server supports WFS 2.0

### ISSUE THREAD

**Issue by matsoo** [opengeospatial/ets-wfs11#45]
The test fails because the parser seems to be expecting a WFS 1.1.0 capabilities document despite not sending a version number. 

The WFS 2.0.0 capabilities causes the following parser error:
   Messages from parser p:XMLValidatingParser.GMLSF1:
        Validation error:
  cvc-elt.1.a: Cannot find the declaration of element 'WFS_Capabilities'.
1 validation error detected.

**Comment by jmfischer** [comment]
I can reproduce this as well and getting the same error message.

**Comment by dstenger** [comment]
The ATS has to be updated as well: https://github.com/opengeospatial/ets-wfs11/blob/master/src/site/markdown/ats-wfs11-basic-cc/GetCapabilities/GET/BasicGetCapabilities-GET-tc12.md

Proposed approach for implementation:
 * Remove schema validation agains 1.1.0 schema.
 * Parse values of ows:ServiceTypeVersion elements and determine the highest version.
 * Update check on attribute wfs:WFS_Capabilities/@version and verify if value of highest version (from previous step) matches the value of this attribute.

**Comment by dstenger** [comment]
Fixed in pull request #49.

**Comment by dstenger** [comment]
Pull request was merged to master branch. This fix will be part of the next release.
