### ISSUE TITLE
Test wfs:wfs-1.1.0-Basic-DescribeFeatureType-POST-tc3 fails

### ISSUE THREAD

**Issue by jmfischer** [opengeospatial/ets-wfs11#46]
Hi,

the test *wfs:wfs-1.1.0-Basic-DescribeFeatureType-POST-tc3* fails:

Error in call to extension function {public static boolean org.opengis.cite.wfs11.GetFeatureTestConditions.checkFeatureTypesDescribedInSchema(org.w3c.dom.Node,org.w3c.dom.Node) throws java.lang.Exception}: Exception in extension function org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 24; Invalid byte 2 of 3-byte UTF-8 sequence.
Result: Failed

I'm not shure the failure is in our Response, because there is no "strange" character at this position or it is the Test itself.

Our Response is (snippet):

      <?xml version="1.0" encoding="utf-8" ?>
      <schema targetNamespace="http://cite.opengeospatial.org/gmlsf" xmlns="http://www.w3.org  /2001/XMLSchema" elementFormDefault="qualified" xmlns:gml="http://www.opengis.net/gml"  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
     <import namespace="http://www.opengis.net/gml" schemaLocation="http://services.interactive-instruments.de/cite2013wfs/cite/schema/ogc/gml/3.1.1/base/gml.xsd"/>
      <element name="AggregateGeoFeature" substitutionGroup="gml:_Feature" type="sf:AggregateGeoFeatureType"/>
     <element name="EntitéGénérique" substitutionGroup="gml:_Feature" type="sf:EntitéGénériqueType"/>
      <element name="PrimitiveGeoFeature" substitutionGroup="gml:_Feature" type="sf:PrimitiveGeoFeatureType"/>

BR
Jean-Michel

**Comment by jmfischer** [comment]
@bermud 
Hi Luis,

just discovered it is the "EntitéGénérique" FeatureType. I removed this FeatureType from the WFS-Configuration and now the Tests pass.

BR
Jean-Michel

**Comment by bermud** [comment]
@jmfischer. Great to know. Will close this issue.
