### ISSUE TITLE
wfs:wfs-1.1.0-Basic-GetCapabilities-tc13 is failing

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs11#52]
wfs:wfs-1.1.0-Basic-GetCapabilities-tc13

 Request : http://localhost:19090/maps?&version=1.1.0&request=GetCapabilities
 Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException
 Result: Failed

**Comment by dstenger** [comment]
Can you please check what your server returns when you send following request? http://localhost:19090/maps?&version=1.1.0&request=GetCapabilities

**Comment by Vinni0803** [comment]
Yes, this url is not working properly, it says Bad Gateway. So, i have changed the server config file and  this issue is resolved.
