### ISSUE TITLE
Test Name : wfs:wfs-1.1.0-Basic-DescribeFeatureType-POST-tc3

### ISSUE THREAD

**Issue by Vinni0803** [opengeospatial/ets-wfs11#53]
For  DescribeFeatureType request without TYPENAME param it gives : 
       
    <xs:element name='basicpolygons' type='tows:basicpolygonsType' substitutionGroup='gml:_Feature' />
  
    <xs:complexType name='basicpolygonsType'>
     <xs:complexContent>
     <xs:extension base='gml:AbstractFeatureType'>
     <xs:sequence>
     <xs:element name ='id' nillable='true' minOccurs='0' maxOccurs='1'>
    <xs:simpleType><xs:restriction base='string'><xs:maxLength value='64'/></xs:restriction>      </xs:simpleType></xs:element>   
     <xs:element name ='geom' type='gml:MultiSurfacePropertyType'   nillable='true' minOccurs='0' maxOccurs='1'/>
    </xs:sequence>
    </xs:extension>
     </xs:complexContent>
    </xs:complexType>

For GetCapabilities request : 

    <FeatureType xmlns:tows="http://www.xxxxxx.com/">
    <Name>tows:basicpolygons</Name>
    <Title>BasicPolygons</Title>
     <DefaultSRS>urn:ogc:def:crs:EPSG::4326</DefaultSRS>
    <ows:WGS84BoundingBox>
    <ows:LowerCorner>-2.000000 -1.000000</ows:LowerCorner>
    <ows:UpperCorner>2.000000 6.000000</ows:UpperCorner>
    </ows:WGS84BoundingBox>
    </FeatureType>
    <FeatureType xmlns:tows="http://www.xxxxxx.com/">
    <Name>tows:buildings</Name>
    <Title>Buildings</Title>
    <DefaultSRS>urn:ogc:def:crs:EPSG::4326</DefaultSRS>
    <ows:WGS84BoundingBox>
    <ows:LowerCorner>0.000800 0.000500</ows:LowerCorner>
    <ows:UpperCorner>0.002400 0.001000</ows:UpperCorner>
     </ows:WGS84BoundingBox>
    </FeatureType>

Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 85 on line 95 in {..., $describeFeatureTypeReque...}:
    Cannot find a matching 2-argument function named {java:org.opengis.cite.wfs11.GetFeatureTestConditions}checkFeatureTypesDescribedInSchema(); SystemID: file:/E:/OGC_ComplianceTest/TE_BASE/work/_OGC_ComplianceTest_TE_BASE_scripts_wfs_1.1.0_ctl_/main/wfs$wfs-1.1.0-Basic-DescribeFeatureType-POST-tc3.test; Line#: 95; Column#: -1
Failed to compile stylesheet. 1 error detected.

**Comment by Vinni0803** [comment]
This is related to teamengine build, as this test case is getting passed when i'm testing WFS on ogc's site.

**Comment by dstenger** [comment]
@Vinni0803, the function "checkFeatureTypesDescribedInSchema" (with two arguments) cannot be found.
As this function is implemented in Java, please make sure that the Java libraries are installed correctly.
The libraries can be found inside following zip file "ets-wfs11-deps.zip". This file has to be extracted into "teamengine/WEB-INF/lib".

**Comment by dstenger** [comment]
Please confirm if this hint solves your problem.

**Comment by Vinni0803** [comment]
Yes, this solved my problem.
Thanks @dstenger .
