### ISSUE TITLE
Failures in "Basic" Testsuite due to functions written in Java: "Invalid byte 2 of 3-byte UTF-8 sequence"

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs11#55]
Three tests fail with both RIs if the "Basic" Testsuite is used. All three test failures originate in Java functions.

RIs:
- http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs110?service=WFS&request=GetCapabilities
- http://services.interactive-instruments.de/cite-xs-46/cite/cgi-bin/wfs110/wfs/wfs?request=GetCapabilities&service=WFS

Failed tests:
- wfs:wfs-1.1.0-Basic-DescribeFeatureType-POST-tc3
- wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3
- wfs:wfs-1.1.0-Basic-GetFeature-tc5

Failures:
- Error in call to extension function {public static boolean org.opengis.cite.wfs11.GetFeatureTestConditions.checkFeatureTypesDescribedInSchema(org.w3c.dom.Node,org.w3c.dom.Node) throws java.lang.Exception}: Exception in extension function org.xml.sax.SAXParseException; lineNumber: 120; columnNumber: 26; Invalid byte 2 of 3-byte UTF-8 sequence.
- Error in call to extension function {public static boolean org.opengis.cite.wfs11.GetFeatureTestConditions.checkFeatureTypesDescribedInSchema(org.w3c.dom.Node,org.w3c.dom.Node) throws java.lang.Exception}: Exception in extension function org.xml.sax.SAXParseException; lineNumber: 120; columnNumber: 26; Invalid byte 2 of 3-byte UTF-8 sequence.
- Error in call to extension function {public static org.w3c.dom.Node org.opengis.cite.wfs11.GetFeatureTestExtension.findFeatureTypeAndPropertyName(org.w3c.dom.Node) throws java.lang.Exception}: Exception in extension function org.xml.sax.SAXParseException; lineNumber: 166; columnNumber: 21; Invalid byte 2 of 3-byte UTF-8 sequence.

This error just occurs on http://cite.opengeospatial.org/teamengine/ (not reproducible on our internal test environment).

**Comment by bermud** [comment]
@rjmartell,  can you please advise on this issue?

**Comment by rjmartell** [comment]
I just ran revision 1.27 of the test suite in teamengine 4.7.1 against the deegree-3.3.14 RI. I didn't observe any of these failures. Instead, one test failed:

* wfs-1.1.0-Basic-GetFeature-tc4.1: The expression '//wfs:FeatureCollection' is false.

The response included an exception report:

```xml
<ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>Unable to resolve external object reference to 'http://vancouver1.demo.galdosinc.com/wfs/http?request=GetFeature&amp;service=WFS&amp;version=1.1.0&amp;typename=sf:PrimitiveGeoFeature#f205': http://vancouver1.demo.galdosinc.com/wfs/http?request=GetFeature&amp;service=WFS&amp;version=1.1.0&amp;typename=sf:PrimitiveGeoFeature#f205</ows:ExceptionText>
  </ows:Exception>
```

This is a test for XLink resolution: "The @traverseXlinkDepth and @traverseXlinkExpiry attributes shall be ignored if the service does not implement the WFS-XLink conformance class". But what if it is supported, and a link cannot be dereferenced as indicated here?

**Comment by dstenger** [comment]
You have to run the "Basic" / "Core" test suite instead of the "Full" test suite (can be selected on main GUI page). Then those errors occur.

We are aware of the above mentioned error which is already fixed for the next version of the RI. In addition, the current Basic WFS CC will be replaced by the "Basic" / "Core" test suite which does not contain the error. So, no further work is required regarding the previous mentioned issue.

The bug discussed in the description of this issue still occurs.

**Comment by dstenger** [comment]
This issue could be related to https://github.com/opengeospatial/ets-wfs20/issues/40.

**Comment by rjmartell** [comment]
Oh. I thought "Full" runs every test, including the core ones.

Upon selecting the "Core" tests, I see several stylesheet compilation errors reported:

```
Cannot find a matching 2-argument function named {java:org.opengis.cite.wfs11.GetFeatureTestConditions}checkFeatureTypesDescribedInSchema(); 
Failed to compile stylesheet. 1 error detected.

Cannot find a matching 2-argument function named {java:org.opengis.cite.wfs11.GetFeatureTestConditions}checkFeatureTypesDescribedInSchema(); 
Failed to compile stylesheet. 1 error detected.

Cannot find a matching 1-argument function named {java:org.opengis.cite.wfs11.GetFeatureTestExtension}findFeatureTypeAndPropertyName();
Cannot find a matching 2-argument function named {java:org.opengis.cite.wfs11.GetFeatureTestConditions}checkFeaturesMatchingFilter(); 
Failed to compile stylesheet. 2 errors detected.
```

**Comment by bermud** [comment]
@dstenger, is the still an issue?

**Comment by dstenger** [comment]
Yes, this issue is still not fixed.

To reproduce the error you have to execute the "Basic" Testsuite on http://cite.opengeospatial.org/teamengine/ (not "Full").

It is hard for us to work on that issue as we cannot reproduce it on our internal environment.
The issue is clearly connected to encoding settings.

**Comment by dstenger** [comment]
We will provide a TEAM Engine session and more detailed information about this bug.

**Comment by dstenger** [comment]
The error still occurs in ```Basic``` test suite.

Service used for testing: http://cite.deegree.org/deegree-webservices-3.4-RC1/services/wfs110?service=WFS&request=GetCapabilities

Log file is attached to this issue.

**Comment by bermud** [comment]
@rjmartell  Can you please helps us figure out what is going on with this test. It seems RIs are  not passing.

**Comment by du002cl** [comment]
Any update on this? We are seeing the same issues when trying to run against latest 1.1 Test Suite Version

**Comment by dstenger** [comment]
The bug is still occurring on http://cite.opengeospatial.org/teamengine/.
We are currently working on a solution for this issue.

**Comment by dstenger** [comment]
The reason for the bug is definitely related to a wrong encoding set in the JVM.

To solve the issue the file encoding can be set as a Java property. The correct encoding is "UTF-8":
```
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
```

After setting this property the Tomcat of the TEAM Engine has to be restarted and must, of course, use the property (e.g. it is set in setenv.sh).

**Comment by bermud** [comment]
Suggest to contact Kevin about it.

**Comment by lgoltz** [comment]
Service used for testing from https://github.com/opengeospatial/ets-wfs11/issues/55#issuecomment-258426209 is outdated, the following can be used instead: http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs110?service=WFS&request=GetCapabilities

**Comment by kstegemoller** [comment]
This
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
is now active on production.

Running this URL
http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs110?service=WFS&request=GetCapabilities

went from 3 failing before the change to all passing after changing to UTF-8.
