### ISSUE TITLE
tests wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3.1 failing

### ISSUE THREAD

**Issue by ranadeepak** [opengeospatial/ets-wfs11#58]
Hi,
I tried running the ets-wfs11 test suite against my WFS 1.1.0 webserver. All of the the test cases are passing except the 4 listed below:
1. wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3.1
2. wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3.2
3. wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3.3
4. wfs:wfs-1.1.0-Basic-DescribeFeatureType-tc3.4

These test cases expect a valid response even if the mandatory parameters 'SERVICE', 'VERSION' are missing in the POST request. But as per the OGC WFS 1.1.0 spec(http://portal.opengeospatial.org/files/?artifact_id=8339) section 14.4. These request parameters are mandatory for all operations(except 'VERSION' in GetCapabilities)

I verified the same with MapServer with request: http://demo.opengeo.org/geoserver/ows?service=wfs&version=1.1.0&request=DescribeFeatureType

It also returns  an ExceptionReport as my server is.

Please let me know if I am missing something or any update is required in the test suite!

**Comment by ranadeepak** [comment]
I even tried the reference server: http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs110?service=WFS&request=DescribeFeatureType. It also returns Exception report

**Comment by dstenger** [comment]
Thank you for reporting this issue. We will do further investigation.

**Comment by lgoltz** [comment]
For further investigations we need some more detailed information. Can you provide the URL of your service? Or at least the log files exported from the session? 
We assume you executed the official WFS 1.1.0 Testuite [1] , selecting the profile 'Full'? 

[1] http://cite.opengeospatial.org/teamengine

**Comment by ranadeepak** [comment]
Hi
I realized the reason for this fix. Actually, there is difference in WFS 1.1.0 DescribeFeatureType POST and GET request. For DescribeFeatureType GET request both and 'service' and 'version' are mandatory. Whereas the DescribeFeatureType POST schema says 'service' and 'version' are optional and defaults to 'WFS' and '1.1.0'. So I have updated our service for POST and setting the respective default values in case they are missing.

If this difference is added explicitel, then this bug gets nullified.

I am using an onprem server. So not sure if the service can be hit publically.

Yes I am running the offcial WFS 1.1.0 TestSuite with'Full' profile.

**Comment by dstenger** [comment]
Hi,
is your problem solved now or do you need any further help?
And would you propose any further actions regarding the ETS (e.g. updating the documentation)?

**Comment by ranadeepak** [comment]
Hi,
My problem is solved but just wanted to confirm that why do we have this difference in GET and POST request. Is this difference documented in OGC spec for WFS 1.1.0.

**Comment by dstenger** [comment]
Section 14 of the WFS 1.1.0 spec is about KVP.
Section 7.8 describes the common XML attributes including "version" and "service" (although, it is not clearly explained if they are mandatory or not). As the schema marks them as optional, they should be handled as optional parameters.

**Comment by ranadeepak** [comment]
This issue was because of that missing clearification :) . I think this issue can be closed now!

Thanks for all your responses!
