### ISSUE TITLE
wfs-1.1.0-Transaction-tc13.1: Confirming that features were deleted

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-wfs11#59]
It is expected that three features were successfully deleted. To confirm this, the `wfs:GetFeatureByName` test is called a total of 9 times, since three calls appear within an xsl:for-each instruction that selects the feature identifiers from the initial insert request.

The feature identifiers are never actually used in the GetFeature requests, which filter on the gml:name property. A GET request with the `featureid` parameter would be a more straightforward way to confirm the absence of the features. Or just remove the xsl:for-each instruction.

**Comment by rjmartell** [comment]
In the `wfs:GetFeatureByName` test (in asserts.ctl), the entity body is enclosed by a CDATA section for some reason. This has the effect of escaping the XML markup, which seems very odd.

**Comment by rjmartell** [comment]
The [deegree 3.3.14 reference implementation](http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs110?service=WFS&request=GetCapabilities) fails this test. Three of the nine GetFeature requests (all with typeName="sf:EntitéGénérique") produce an exception report:

```
<ows:Exception exceptionCode="InvalidRequest">
      <ows:ExceptionText>Invalid UTF-8 middle byte 0x47 (at char #212, byte #-1)</ows:ExceptionText>
</ows:Exception>
```

**Comment by dstenger** [comment]
> The [deegree 3.3.14 reference implementation](http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs110?service=WFS&request=GetCapabilities) fails this test. Three of the nine GetFeature requests (all with typeName="sf:EntitéGénérique") produce an exception report:
> 
> ```
> <ows:Exception exceptionCode="InvalidRequest">
>       <ows:ExceptionText>Invalid UTF-8 middle byte 0x47 (at char #212, byte #-1)</ows:ExceptionText>
> </ows:Exception>
> ```
>   

deegree has a problem with the encoding there:
```
  <ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
      <ows:ExceptionText>Feature type with name '{http://cite.opengeospatial.org/gmlsf}Entit?G?n?rique' is not served by this WFS.</ows:ExceptionText>
  </ows:Exception>
```

But this is not related to the originally reported bug.

**Comment by dstenger** [comment]
When the provided test server is used following exception is returned by the service:
```
   Response from parser p:XMLValidatingParser.GMLSF1:
      <ExceptionReport xmlns="http://www.opengis.net/ows" version="1.1.0">
  <Exception exceptionCode="OperationNotSupported">
      <ExceptionText>(Error.NoXMLProcessorFound)No processor can be found to process the XML message, it usually means that either the message is wrong or the version attribute is missing or invalid.</ExceptionText>
  </Exception>
   <!--Response received in [58] milliseconds--></ExceptionReport>

Message d149e35607_1:
   FAILURE: Expected valid wfs:FeatureCollection in response.
```

So, the failure occurs when inserting or deleting the features.

We will do further investigation on this issue.

**Comment by dstenger** [comment]
Relevant commit: https://github.com/opengeospatial/ets-wfs11/commit/9098d89d3edfdbece7c53c7aff6e58e01f25fc2d
