### ISSUE TITLE
Update Test Notes - Overview and Structure of the test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs11#61]
Update the notes for developers to understand very clear the scope of the basic

- Core (no test data)
- Basic 
- Transaction
- Locking
- XLink

**Comment by dstenger** [comment]
Actually, the Core test suite bases on the Basic CC (as defined in the WFS 1.1.0 specification).

I have just updated the GUI for starting a WFS 1.1.0 test run:
```
 x Full
   x WFS-Basic (Required)
   x WFS-Transaction
   x WFS-XLink
 x Core (No test data are required. Bases on Basic WFS conformance class.)
```

Are there any suggestions for further improvements regarding the GUI to start WFS 1.1.0 tests?

**Comment by dstenger** [comment]
Pull request was created (#62) and will be part of the next release.

**Comment by dstenger** [comment]
Pull request #62 was merged into master branch (after having done tests).
Fix will be part of the upcoming release.
