### ISSUE TITLE
Replace Basic-WFS CC with Core test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs11#64]
As the data agnostic Core test suite covers exactly the Basic conformance class, the old Basic-WFS CC can be replaced with the Core test suite.

This will lead to an always data agnostic Basic-WFS CC.

**Comment by dstenger** [comment]
Changes that have to be done:
 * Option between "Full" and "Core" is removed.
 * If Basic-WFS CC is executed, the Core test suite (GET and POST) is executed. There is no way to execute the old data depended Basic-WFS CC anymore.
 * The GUI is updated (regarding description and texts).
 * The index.md is updated.

**Comment by dstenger** [comment]
Pull request with implementation of the enhancement was created: #65.

**Comment by dstenger** [comment]
Please review the changes and give us feedback.
We would propose intensive testing of the changes.

**Comment by bermud** [comment]
The changes looks good. I made minor edits https://github.com/opengeospatial/ets-wfs11/commit/0d8832e40d59345f77f4ef17cde0bec247d4d197

Suggest to clarify further this in the index.md file the following:

> "Note that GMLSF Levels 0 and 1 **DO NOT** support the use of feature collections through WFS interfaces. The collections defined here are provided
> for convenience only and they cannot themselves be treated as GML features."

**Comment by dstenger** [comment]
Thank you for the adjustments! I have merged them into the feature branch.

**Comment by dstenger** [comment]
The quoted section of the index.md was removed as this information is outdated.

**Comment by dstenger** [comment]
Fix was successfully tested and merged into master branch. It will be part of the upcoming release.
