### ISSUE TITLE
Add conformance class configuration into the wfs11 test

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wfs11#68]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
WFS 1.1.0 specifies the following classes of web feature services (p. 3):
 * Basic WFS
 * XLink WFS
 * Transaction WFS

The ETS groups the test in the following conformance classes (from the main entry point):
 * WFS-Basic: Implements GetCapabilities, DescribeFeatureType and GetFeature requests                                                  
 *  WFS-Transaction: Implements the Transaction request
 * WFS-Locking: Implements optional LockFeature and GetFeatureWithLock
 * WFS-XLink: Implements the GetGmlObject request and supports (local) XLink processing in GetFeature requests.

With the exception of WFS-Locking these are identical. The WFS 1.1.0 specifies the LockFeature operations as optional part of the _Transaction WFS_. I think the grouping in the ETS is fine so far. 

As already described for the WMS 1.3 ETS we have a problem with the hierarchy depth: the new HTML report allows only a depth of 2, while the ETS has more hierarchy levels.

**Comment by lgoltz** [comment]
Added conformance class configuration: https://github.com/opengeospatial/ets-wfs11/commit/d4938cb54d7eb920ebd9998371ac78ed92eb5ec8

Cause of https://github.com/opengeospatial/teamengine/issues/263 the output contains only the link to old test report.

**Comment by lgoltz** [comment]
With the fix https://github.com/opengeospatial/teamengine/pull/264 the new HTML report is empty.

**Comment by keshav-nangare** [comment]
According to documentation all conformance classes should be in the main.ctl file i.e. starting point of the test.

If we added this conformance classes in other places(files) then the CtlEarlReporter classes is not able to identify the conformance classes. So its mandatory to add in main.ctl file.

**Comment by lgoltz** [comment]
@keshav-nangare Is the starting point decisive or the hierarchy level? A test suite could be completely scripted in one CTL file but with arbitrary hierarchy levels.

**Comment by keshav-nangare** [comment]
To maintain the hierarchy level of conformance classes and its sub-tests. The CtlEarlReport will get the first level as conformance classes and then it will process all the sub-tests.

**Comment by lgoltz** [comment]
Test was restructured that the configuration of the conformances classes is on the second level. Previously the main test `wfs:wfs-main` called the test `wfs:readiness-tests` which called the test configured as conformance class (configured in https://github.com/opengeospatial/ets-wfs11/issues/68#issuecomment-342425476).
Now the test  `wfs:wfs-main` calls the test `wfs:readiness-tests` which was configured as basic conformance class. Furthermore the call of the tests already configured as conformance class  are called by the test  `wfs:wfs-main` now,  too.

Commit: https://github.com/opengeospatial/ets-wfs11/commit/a42dc5bd9c4482d9decba289fb5d8e711268693c
