### ISSUE TITLE
WFS 1.1.0 DataSet

### ISSUE THREAD

**Issue by papalav** [opengeospatial/ets-wfs11#69]
This is a query regarding WFS Dataset available at this URL - 
http://cite.opengeospatial.org/teamengine/about/wfs/1.1.0/site/data-wfs-1.1.0.zip

The Dataset contains schema for "ComplexGeoFeatureType" in the XSD file "cite-gmlsf1.xsd"

On comparing the xsd with a DecribeFeatureType response from Reference Implementation - 
http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs110?service=WFS&request=DescribeFeatureType&version=1.1.0

It is observed that the properties of "ComplexGeoFeatureType" are differently defined.

1. **element name="reference" minOccurs="0" type="gml:FeaturePropertyType"** is defined in the DescribeFeatureType response which is **not present in the downloadable Dataset schema for "ComplexGeoFeature"**
2. As a result, "**Test wfs:wfs-1.1.0-Transaction-tc21.1**" is executed successfully for the Reference Implementation, but implementing servers that have loaded the dataset will find issues while passing this Test Case.
3. Please let us know if the DataSet has been updated or the TestCase is going to be revised (since it seems related to XLINKS, but the test case is executed even when XLINK is not selected)

**Comment by dstenger** [comment]
Thank you for reporting the issue. We will do further analysis.

**Comment by lgoltz** [comment]
The described problem is  comprehensible. In the downloadable archive the schema 'cite-gmlsf1.xsd' does not include the declaration **reference**  and the test data does not include the property. 
The schema in the ets [1] includes the declaration, but the test data [2] does not include a property for it. 

The test  **wfs:wfs-1.1.0-Transaction-tc21.1** inserts two features, one  with a **reference** to the other (request body [3]). The test is executed if SF-1 : Level 1 is selected.

It seems that the downloadable schema is outdated and needs an updated. 

[1] https://github.com/opengeospatial/ets-wfs11/blob/master/src/main/resources/xsd/ogc/cite/cite-gmlsf1.xsd
[2] https://github.com/opengeospatial/ets-wfs11/blob/master/src/main/resources/data/sf-1/dataset-sf1-insert.xml
[3] https://github.com/opengeospatial/ets-wfs11/blob/master/src/main/scripts/ctl/wfs-transaction/Transaction/gmlsf-1/wfs-1.1.0-Transaction-tc21.1.body.xml

**Comment by dstenger** [comment]
We will update the schema on http://cite.opengeospatial.org/teamengine/.

For now, following schema can be used: https://raw.githubusercontent.com/opengeospatial/ets-wfs11/master/src/main/resources/xsd/ogc/cite/cite-gmlsf1.xsd

**Comment by dstenger** [comment]
Test data were updated and general structure was improved. This fix is provided by pull request #71 and will be part of the next release.
Till then, the previously mentioned workaround has to be used.
