### ISSUE TITLE
OWS 1.1.0 schemas missing

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wfs11#76]
document 04-094 section 7.7 specify that exceptions should use OWS 1.1.0 but those schemas are not in wfs\1.1.0\resources\xsd\ogc\ows and test fails with:
_
Testing wfs:wfs-1.1.0-Basic-DescribeFeatureType-POST-tc4 type Mandatory in Test Mode with defaultResult Pass (s0004/d68e38807_1/d68e636_1/d68e28820_1/d68e6470_1)...
                     Assertion: The following attributes are required for all XML request entities: @version (default '1.1.0'); @service
      (default 'WFS').

Validation error:
  cvc-elt.1.a: Cannot find the declaration of element 'ows:ExceptionReport'.
1 validation error detected._

**Comment by coim32** [comment]
This is the ows exception response I'm testing with, it is correct?
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 ../owsExceptionReport.xsd" version="1.1.0">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="service">
    <ows:ExceptionText>Service attribute is not specified as WFS</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>

**Comment by dstenger** [comment]
Thank you for reporting this.
Can you provide a test service we can use to reproduce the behaviour?

**Comment by coim32** [comment]
not an issues
