### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs11#82]
See opengeospatial/ets-wms13#56 for instructions.

Please use following service implementation: http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs110?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
@keshav-nangare 
Configuration is outdated. Please do an update (just chapter `System tests`): https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI#system-tests

**Comment by keshav-nangare** [comment]
Updated the configuration to latest. Fixed with this commit: e2d4aad. Changes are pushed in same PR.
